{
 "title": "Ceph - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Cluster",
    "query": "label_values(ceph_mon_quorum_status, job)"
   },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mon_quorum_status{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_objects{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\"}/ceph_cluster_total_bytes{job=\"$job\"}*100"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\"}) - count(ceph_osd_in{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{job=\"$job\"})"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OSD Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{job=\"$job\"}",
     "legendFormat": "{{ceph_daemon}} apply"
    },
    {
     "expr": "ceph_osd_commit_latency_ms{job=\"$job\"}",
     "legendFormat": "{{ceph_daemon}} commit"
    }
   ]
  },
  {
   "title": "MDS Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(ceph_mds_reply_latency_sum{job=\"$job\"} / clamp_min(ceph_mds_reply_latency_count{job=\"$job\"}, 1)) or vector(0)",
     "legendFormat": "latency"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PGs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_active{job=\"$job\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_clean{job=\"$job\"})",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(ceph_pg_peering{job=\"$job\"})",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum(ceph_pg_degraded{job=\"$job\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{job=\"$job\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_unclean_pgs{job=\"$job\"})",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum(ceph_pg_undersized{job=\"$job\"})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum(ceph_pg_incomplete{job=\"$job\"})",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(ceph_pg_forced_backfill{job=\"$job\"})",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum(ceph_pg_inconsistent{job=\"$job\"})",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum(ceph_pg_forced_recovery{job=\"$job\"})",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum(ceph_pg_creating{job=\"$job\"})",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum(ceph_pg_wait_backfill{job=\"$job\"})",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum(ceph_pg_deep{job=\"$job\"})",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum(ceph_pg_scrubbing{job=\"$job\"})",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum(ceph_pg_recovering{job=\"$job\"})",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum(ceph_pg_repair{job=\"$job\"})",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum(ceph_pg_down{job=\"$job\"})",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(ceph_pg_peered{job=\"$job\"})",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum(ceph_pg_backfill{job=\"$job\"})",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum(ceph_pg_remapped{job=\"$job\"})",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum(ceph_pg_backfill_toofull{job=\"$job\"})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Objects Unfound / Degraded / Misplaced",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_num_objects_unfound{job=\"$job\"}",
     "legendFormat": "Unfound"
    },
    {
     "expr": "ceph_num_objects_degraded{job=\"$job\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_num_objects_misplaced{job=\"$job\"}",
     "legendFormat": "Misplaced"
    }
   ]
  },
  {
   "title": "Objects in the Cluster",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Faulty PGs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_degraded{job=\"$job\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{job=\"$job\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_pg_undersized{job=\"$job\"})",
     "legendFormat": "Undersized"
    }
   ]
  }
 ]
}